{
 "title": "Karpenter Performance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_reconcile_time_seconds_count{controller=~\"provisioner|disruption|disruption.queue|node.termination|nodeclaim.termination|nodeclaim.lifecycle|interruption|eviction-queue\"}, controller)"
    }
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Node Termination Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "karpenter_nodes_termination_duration_seconds{k8s_cluster_name=~\"$cluster_name\",quantile=\"0\"}",
     "legendFormat": "Min-{{instance}}"
    },
    {
     "expr": "karpenter_nodes_termination_duration_seconds{k8s_cluster_name=~\"$cluster_name\",quantile=\"0.5\"}",
     "legendFormat": "P50-{{instance}}"
    },
    {
     "expr": "karpenter_nodes_termination_duration_seconds{k8s_cluster_name=~\"$cluster_name\",quantile=\"0.9\"}",
     "legendFormat": "P90-{{instance}}"
    },
    {
     "expr": "karpenter_nodes_termination_duration_seconds{k8s_cluster_name=~\"$cluster_name\",quantile=\"0.99\"}",
     "legendFormat": "P99-{{instance}}"
    },
    {
     "expr": "karpenter_nodes_termination_duration_seconds{k8s_cluster_name=~\"$cluster_name\",quantile=\"1\"}",
     "legendFormat": "Max-{{instance}}"
    }
   ]
  },
  {
   "title": "Pod Startup Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "karpenter_pods_startup_duration_seconds{k8s_cluster_name=~\"$cluster_name\",quantile=\"0\"}",
     "legendFormat": "Min-{{instance}}"
    },
    {
     "expr": "karpenter_pods_startup_duration_seconds{k8s_cluster_name=~\"$cluster_name\",quantile=\"0.5\"}",
     "legendFormat": "P50-{{instance}}"
    },
    {
     "expr": "karpenter_pods_startup_duration_seconds{k8s_cluster_name=~\"$cluster_name\",quantile=\"0.9\"}",
     "legendFormat": "P90-{{instance}}"
    },
    {
     "expr": "karpenter_pods_startup_duration_seconds{k8s_cluster_name=~\"$cluster_name\",quantile=\"0.99\"}",
     "legendFormat": "P99-{{instance}}"
    },
    {
     "expr": "karpenter_pods_startup_duration_seconds{k8s_cluster_name=~\"$cluster_name\",quantile=\"1\"}",
     "legendFormat": "Max-{{instance}}"
    }
   ]
  },
  {
   "title": "Controller Reconciliation Latency [$controller]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0, rate(controller_runtime_reconcile_time_seconds_bucket{k8s_cluster_name=~\"$cluster_name\",controller=\"$controller\"}[10m]))",
     "legendFormat": "Min-{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.5, rate(controller_runtime_reconcile_time_seconds_bucket{k8s_cluster_name=~\"$cluster_name\",controller=\"$controller\"}[10m]))",
     "legendFormat": "P50-{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(controller_runtime_reconcile_time_seconds_bucket{k8s_cluster_name=~\"$cluster_name\",controller=\"$controller\"}[10m]))",
     "legendFormat": "P90-{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(controller_runtime_reconcile_time_seconds_bucket{k8s_cluster_name=~\"$cluster_name\",controller=\"$controller\"}[10m]))",
     "legendFormat": "P99-{{instance}}"
    },
    {
     "expr": "histogram_quantile(1, rate(controller_runtime_reconcile_time_seconds_bucket{k8s_cluster_name=~\"$cluster_name\",controller=\"$controller\"}[10m]))",
     "legendFormat": "Max-{{instance}}"
    }
   ]
  },
  {
   "title": "Controller Reconciliation Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{k8s_cluster_name=~\"$cluster_name\"}[10m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}