{
 "title": "Kubernetes Storage Volumes (Namespace)",
 "description": "Shows information and alerts related to Kubernetes Storage / Volumes (namespace level).",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "k8s_cluster_name", "label": "K8s cluster name", "query": { "query": "label_values(k8s_cluster_name)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "pvc_percent_used_warning_threshold",
    "label": "PVC % Used Warning Threshold",
    "query": "80"
   },
   {
    "name": "persistentvolumeclaim",
    "query": {
     "query": "label_values(kubelet_volume_stats_used_bytes {namespace=\"$namespace\"}, persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Volumes Full in Week Based on Daily Use Rate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 14, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n count (\n   (kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"})\n   and\n   (predict_linear(kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}[1d], 7 * 24 * 60 * 60) < 0)\n )\n)\nor\nvector(0)",
       "legendFormat": "alerts"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"})) >= ($pvc_percent_used_warning_threshold / 100)) or vector (0)"
      }
     ]
    },
    {
     "title": "Unbound PVCs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 7, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(count(kube_persistentvolumeclaim_status_phase{k8s_cluster_name=~\"$k8s_cluster_name\",phase!=\"Bound\"} > 0) or (vector(0)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Alert Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Volumes Full in Week Based on Daily Use Rate - Current",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "(\n  (\n    (kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"} ) \n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}[1w], 7 * 24 * 60 * 60) < 0)\n  )\n)"
      }
     ]
    },
    {
     "title": "Volumes Full in Week Based on Daily Use Rate - Alert History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "# of Alerts" }
     ],
     "targets": [
      {
       "expr": "(\n  (\n    ((kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"} ) * 0) + 1\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Volumes Full in Week Based on Daily Use Rate -  Predicted Available Space History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 15 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "1 Week Predicted Available Space"
      }
     ],
     "targets": [
      {
       "expr": "(\n  (predict_linear(kubelet_volume_stats_available_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}[1d], 7 * 24 * 60 * 60) < 0)\n)",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold Stats - Current",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "(\n  (kube_persistentvolumeclaim_info {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"})\n  and\n  (\n    (\n      (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}))\n      /\n      (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}))\n    ) >= ($pvc_percent_used_warning_threshold / 100)\n  )\n)"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes {namespace=\"$namespace\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$namespace\"})) >= ($pvc_percent_used_warning_threshold / 100)"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Total # of Alerts" }
     ],
     "targets": [
      {
       "expr": "(\n  ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"})) * 0 +1)\n  and\n  (\n    (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}))\n  ) >= ($pvc_percent_used_warning_threshold / 100)\n)",
       "legendFormat": "PVC Running Above % Used Warning Threshold - {{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bound PVCs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum (kube_persistentvolumeclaim_status_phase{k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\",phase=\"Bound\"} ==1 )) or vector(0)"
      }
     ]
    },
    {
     "title": "PVC Stats",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": " (kube_persistentvolumeclaim_info { k8s_cluster_name=~\"$k8s_cluster_name\",namespace = \"$namespace\" })"
      },
      {
       "expr": "(1-max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info { k8s_cluster_name=~\"$k8s_cluster_name\",namespace = \"$namespace\" }) ) unless (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes { k8s_cluster_name=~\"$k8s_cluster_name\",namespace = \"$namespace\" })) or ((max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info { k8s_cluster_name=~\"$k8s_cluster_name\",namespace = \"$namespace\" }) ) and (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes { k8s_cluster_name=~\"$k8s_cluster_name\",namespace = \"$namespace\" })))"
      },
      {
       "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes { k8s_cluster_name=~\"$k8s_cluster_name\",namespace = \"$namespace\" })"
      },
      {
       "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes { k8s_cluster_name=~\"$k8s_cluster_name\",namespace = \"$namespace\" })"
      },
      {
       "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes { k8s_cluster_name=~\"$k8s_cluster_name\",namespace = \"$namespace\" })"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes { k8s_cluster_name=~\"$k8s_cluster_name\",namespace = \"$namespace\" })) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes { k8s_cluster_name=~\"$k8s_cluster_name\",namespace = \"$namespace\" }))"
      }
     ]
    }
   ]
  },
  {
   "title": "Use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Running PVCs % Used",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"})) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"})) * 100",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "All Running PVCs Used Bytes",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}))",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Use vs Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$persistentvolumeclaim",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "repeat": "persistentvolumeclaim",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\"}))",
       "legendFormat": "Used"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\", persistentvolumeclaim=\"$persistentvolumeclaim\"}))",
       "legendFormat": "Capacity"
      }
     ]
    }
   ]
  },
  {
   "title": "Use Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hourly Volume Use Rate",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}[1h])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Daily Volume Use Rate",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}[1d])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Weekly Volume Use Rate",
     "type": "graph",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes {k8s_cluster_name=~\"$k8s_cluster_name\",namespace=\"$namespace\"}[1w])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  }
 ]
}