{
 "title": "Kubernetes API Server Performance",
 "description": "Latency and cache hit graphs for Kubernetes apiserver.  Useful for observing performance of Amazon EKS clusters.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "API Server Request Rate",
   "type": "graph",
   "description": "API Server Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests in second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "WorkQueue Service Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Service time, µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile (p95)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "90th Percentile (p90)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th Percentile (p50)"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "graph",
   "description": "95th percentile request latency for Kubernetes apiserver component",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Latency, s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "95th Percentile (p95)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "90th Percentile (p90)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "50th Percentile (p50) "
    }
   ]
  },
  {
   "title": "WorkQueue Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Processing time, s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile (p95)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "90th Percentile (p90)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th Percentile (p50)"
    }
   ]
  },
  {
   "title": "ETCD DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes", "label": "ETCD DB Size" }
   ],
   "targets": [
    { "expr": "etcd_db_total_size_in_bytes", "legendFormat": "Endpoint {{endpoint}}" }
   ]
  },
  {
   "title": "ETCD Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s", "label": "Latency, s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile (p95)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "90th Percentile (p90)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th Percentile (p50)"
    }
   ]
  }
 ]
}