{
 "title": "Kubernetes API Server Performance",
 "description": "Latency and cache hit graphs for Kubernetes apiserver.  Useful for observing performance of Amazon EKS clusters.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "API Server Request Rate",
   "type": "timeseries",
   "description": "API Server Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{k8s_cluster_name=~\"$cluster_name\"}[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "WorkQueue Service Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\"}[5m])) by (le))",
     "legendFormat": "95th Percentile (p95)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\"}[5m])) by (le))",
     "legendFormat": "90th Percentile (p90)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\"}[5m])) by (le))",
     "legendFormat": "50th Percentile (p50)"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "timeseries",
   "description": "95th percentile request latency for Kubernetes apiserver component",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\",verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "95th Percentile (p95)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\",verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "90th Percentile (p90)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\",verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "50th Percentile (p50) "
    }
   ]
  },
  {
   "title": "WorkQueue Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\"}[5m])) by (le))",
     "legendFormat": "95th Percentile (p95)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\"}[5m])) by (le))",
     "legendFormat": "90th Percentile (p90)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\"}[5m])) by (le))",
     "legendFormat": "50th Percentile (p50)"
    }
   ]
  },
  {
   "title": "ETCD DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "apiserver_storage_size_bytes{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}} ({{storage_cluster_id}})"
    }
   ]
  },
  {
   "title": "ETCD Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\"}[5m])) by (le))",
     "legendFormat": "95th Percentile (p95)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\"}[5m])) by (le))",
     "legendFormat": "90th Percentile (p90)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_request_duration_seconds_bucket{k8s_cluster_name=~\"$cluster_name\"}[5m])) by (le))",
     "legendFormat": "50th Percentile (p50)"
    }
   ]
  }
 ]
}