{
 "title": "Logging metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Fluent-bit incoming events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(fluentbit_input_records_total{k8s_cluster_name=~\"$cluster_name\",name=~\"tail.*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fluent-bit outgoing events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(fluentbit_output_proc_records_total{k8s_cluster_name=~\"$cluster_name\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logstash incoming events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_in_total{k8s_cluster_name=~\"$cluster_name\"}[$__rate_interval])",
     "legendFormat": "{{pipeline}} pipe on {{instance}}"
    }
   ]
  },
  {
   "title": "Logstash outgoing events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_out_total{k8s_cluster_name=~\"$cluster_name\"}[$__rate_interval])",
     "legendFormat": "{{pipeline}} pipe on {{instance}}"
    }
   ]
  },
  {
   "title": "Logstash events in queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "logstash_node_queue_events{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pipeline}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Logstash heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "logstash_node_mem_heap_max_bytes{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Heap max on {{instance}}"
    },
    {
     "expr": "logstash_node_mem_heap_used_bytes{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Heap used on {{instance}}"
    }
   ]
  },
  {
   "title": "FluentBit Input vs Output Record Rate",
   "type": "timeseries",
   "description": "Tracks FluentBit’s end-to-end log processing — from records ingested to records delivered.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{k8s_cluster_name=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "Input Records"
    },
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{k8s_cluster_name=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "Output Records"
    }
   ]
  },
  {
   "title": "Logstash CPU Usage (% of Limit)",
   "type": "timeseries",
   "description": "Shows Logstash CPU usage as a percentage of the container's CPU limit, grouped by pod.",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sort_desc((sum(rate(container_cpu_usage_seconds_total{container=\"logstash\", k8s_cluster_name=~\"$cluster_name\"}[5m])) by (container, pod) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container=\"logstash\", k8s_cluster_name=~\"$cluster_name\"}) by (container, pod)) * 100)",
     "legendFormat": "{{pod}} - CPU %"
    }
   ]
  },
  {
   "title": "Logstash Memory Usage (% of Limit)",
   "type": "timeseries",
   "description": "Shows Logstash memory usage as a percentage of the container's memory limit, grouped by pod.",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sort_desc((sum(container_memory_working_set_bytes{container=\"logstash\", k8s_cluster_name=~\"$cluster_name\"}) by (container, pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", container=\"logstash\", k8s_cluster_name=~\"$cluster_name\"}) by (container, pod)) * 100)",
     "legendFormat": "{{pod}} - Memory %"
    }
   ]
  },
  {
   "title": "FluentBit Output Issues (Errors, Drops, Retries)",
   "type": "timeseries",
   "description": "Detects issues in FluentBit output processing such as plugin errors, dropped records and retry storms.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{k8s_cluster_name=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "Retries"
    },
    {
     "expr": "sum(rate(fluentbit_output_errors_total{k8s_cluster_name=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(rate(fluentbit_output_dropped_records_total{k8s_cluster_name=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "Dropped Records"
    }
   ]
  },
  {
   "title": "FluentBit Memory Usage (% of Limit)",
   "type": "timeseries",
   "description": "Shows FluentBit memory usage as a percentage of the container's memory limit, grouped by pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sort_desc((sum(container_memory_working_set_bytes{container=\"fluent-bit\", k8s_cluster_name=~\"$cluster_name\"}) by (container, pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", container=\"fluent-bit\", k8s_cluster_name=~\"$cluster_name\"}) by (container, pod)) * 100)",
     "legendFormat": "{{pod}} - Memory %"
    }
   ]
  },
  {
   "title": "Logstash Nodes Up Count",
   "type": "timeseries",
   "description": "Displays the total number of active Logstash nodes reporting as Up",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(logstash_node_up{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "Total Up Nodes"
    }
   ]
  },
  {
   "title": "FluentBit CPU Usage (% of Limit)",
   "type": "timeseries",
   "description": "Shows FluentBit CPU usage as a percentage of the container's CPU limit, grouped by pod.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sort_desc((sum(rate(container_cpu_usage_seconds_total{container=\"fluent-bit\", k8s_cluster_name=~\"$cluster_name\"}[5m])) by (container, pod) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container=\"fluent-bit\", k8s_cluster_name=~\"$cluster_name\"}) by (container, pod)) * 100)",
     "legendFormat": "{{pod}} - CPU %"
    }
   ]
  },
  {
   "title": "FluentBit In-Memory Buffer Usage (MB)",
   "type": "timeseries",
   "description": "Displays the total size (in MB) of logs currently buffered in memory across all FluentBit input plugins.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(fluentbit_input_storage_memory_bytes{k8s_cluster_name=~\"$cluster_name\"}) by (instance, name) / 1024 / 1024",
     "legendFormat": "In-Memory Buffer (MB)"
    }
   ]
  },
  {
   "title": "FluentBit Disk Buffer Usage (MB)",
   "type": "timeseries",
   "description": "Shows total size (in MB) of busy chunks written to disk by FluentBit input plugins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(fluentbit_input_storage_chunks_busy_bytes{k8s_cluster_name=~\"$cluster_name\"}) by (instance, name) / 1024 / 1024",
     "legendFormat": "Total Disk Buffer (MB)"
    }
   ]
  },
  {
   "title": "FluentBit Input Plugin Memory Overlimit",
   "type": "timeseries",
   "description": "Displays which FluentBit input plugins are currently over the memory buffer limit. A flatline means all are correctly under the memory limit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(fluentbit_input_storage_overlimit{k8s_cluster_name=~\"$cluster_name\"}) by (pod, name)",
     "legendFormat": "Overlimit: {{name}}"
    }
   ]
  },
  {
   "title": "Fluent Bit Output Chunk Available Capacity (%)",
   "type": "timeseries",
   "description": "Displays the current available buffer capacity (as a percentage) for each Fluent Bit output plugin, grouped by instance and plugin name. A lower percentage may indicate that output chunks are nearing capacity, which can lead to dropped records if sustained.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(fluentbit_output_chunk_available_capacity_percent{k8s_cluster_name=~\"$cluster_name\"}) by (instance, name)",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "FluentBit Input Ingestion Paused Status",
   "type": "timeseries",
   "description": "Indicates whether FluentBit input ingestion is currently paused per instance.(Greater than 0 = paused, 0 = active.)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(fluentbit_input_ingestion_paused{k8s_cluster_name=~\"$cluster_name\"}) by (instance)",
     "legendFormat": "Paused - {{instance}}"
    }
   ]
  },
  {
   "title": "FluentBit Chunk distribution: In-Memory, On-Disk, Total",
   "type": "timeseries",
   "description": "Tracks how FluentBit distributes log chunks between memory and disk.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fluentbit_storage_fs_chunks_up{k8s_cluster_name=~\"$cluster_name\"}) by (instance)",
     "legendFormat": "In-Memory Chunks - {{instance}}"
    },
    {
     "expr": "sum(fluentbit_storage_fs_chunks{k8s_cluster_name=~\"$cluster_name\"}) by (instance)",
     "legendFormat": "Total Chunks (Memory + On-Disk) - {{instance}}"
    },
    {
     "expr": "sum(fluentbit_storage_fs_chunks_down{k8s_cluster_name=~\"$cluster_name\"}) by (instance)",
     "legendFormat": "On-Disk Chunks - {{instance}}"
    }
   ]
  }
 ]
}