{
 "title": "Logstash app metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Incoming events per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_in_total{k8s_cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pipeline}} pipe on {{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing events per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_out_total{k8s_cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pipeline}} pipe on {{instance}}"
    }
   ]
  },
  {
   "title": "Events in queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "logstash_node_queue_events{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pipeline}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "logstash_node_mem_heap_max_bytes{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Heap max on {{instance}}"
    },
    {
     "expr": "logstash_node_mem_heap_used_bytes",
     "legendFormat": "Heap used on {{instance}}"
    }
   ]
  }
 ]
}