{
 "title": "PingAccess Topology Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Failed Authorizations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trackingId.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "method: \"GET\" AND responseCode: 403 AND cluster_name: $cluster_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Admin API Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT client: 127.0.0.1 AND cluster_name: $cluster_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Successful Authorizations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "trackingId.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "((responseCode: 200 AND NOT authMech: NULL) OR responseCode:401) AND cluster_name: $cluster_name",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}