{
 "title": "PingDirectory Per-Server Dashboard",
 "description": "PingDirectory Metrics by Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "JVM Heap by server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_bytes_used{area=\"heap\",job=\"pd-jmx-exporter\",namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "Heap used on {{instance}}"
    },
    {
     "expr": "sum by (instance) (jvm_memory_bytes_max{area=\"heap\",job=\"pd-jmx-exporter\",namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "Heap max on {{instance}}"
    }
   ]
  },
  {
   "title": "Throughput by Operation and Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "throughput{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Throughput by Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (throughput{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Latency by Operation and Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "response_time{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"} > 0",
     "legendFormat": "{{instance}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Average Operation Latency by Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (instance) (response_time{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"} > 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Live Megabytes by Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (garbage_collection_live_megabytes{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Rate by Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (gcType, size, cause, instance) (rate(garbage_collections{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}[1m]))",
     "legendFormat": "{{instance}}-{{gcType}}-{{size}}-{{cause}}"
    }
   ]
  }
 ]
}