{
 "title": "PingFederate Per-Server Dashboard",
 "description": "PingFederate Metrics by Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "JVM GC CPU, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"pf-jmx-exporter\", namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{instance}} - {{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Old Gen (Tenured) Collected, %",
   "type": "timeseries",
   "description": "JVM GC Old Gen (Tenured) Collected, %\\n\\nFormula: GC Old Gen (Tenured) Collection Usage Used / GC Old Gen (Tenured) Collection Usage Max * 100",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_PS_Old_Gen_CollectionUsage_used{job=\"pf-jmx-exporter\", namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"} or java_lang_Tenured_Gen_CollectionUsage_used{job=\"pf-jmx-exporter\", namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"})/(java_lang_PS_Old_Gen_CollectionUsage_max{job=\"pf-jmx-exporter\", namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"} or java_lang_Tenured_Gen_CollectionUsage_max{job=\"pf-jmx-exporter\", namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingfederate_total_transactions{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total failed transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingfederate_total_failed_transactions{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Time Statistics Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingfederate_response_time_statistics_mean{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Time 90 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(metric_pingfederate_response_time_statistics_90_percentile{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Concurrency Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingfederate_response_concurrency_statistics_mean{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Concurrency 90 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingfederate_response_concurrency_statistics_90_percentile{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Session State Attribute Map Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingfederate_session_state_attribute_map_size{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingfederate_response_statistics_count{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SP Session Registry Map Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingfederate_sp_session_registry_session_map_size{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IDP Session Registry Map Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metric_pingfederate_idp_session_registry_session_map_size{namespace=\"$namespace\",k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}