# Mirrors this private repository to the public pingidentity/ping-cloud-base-patches repository.
name: Mirror to pingidentity/ping-cloud-dashboards

on: push

jobs:
  mirror-to-ping-cloud-dashboards:
    uses: ping-internal/p1as-eng-tools/.github/workflows/mirror-repository.yml@master
    with:
      github-ref: ${{ github.ref}}
      target-repo-ssh-url: "ssh://github.com/pingidentity/ping-cloud-dashboards.git"
    secrets:
      mirror-deploy-ssh-key: ${{ secrets.MIRROR_DEPLOY_SSH_KEY }}
    permissions:
      contents: read
      issues: write